[pytest]
python_files = pytest_*.py
addopts =
  --embedded-services esp,idf
  --strict-markers
  --skip-check-coredump y

markers =
  esp32: run on ESP32 hardware
  generic: generic embedded test

filterwarnings =
  ignore::_pytest.warning_types.PytestExperimentalApiWarning
