[pytest]
python_files = pytest_*.py
addopts =
  --strict-markers

markers =
  esp32: run on ESP32 hardware
  integration: production firmware integration tests
  cli_e2e: CLI end-to-end tests against the real device
  modio: tests that require MOD-IO hardware to be present

filterwarnings =
  ignore::_pytest.warning_types.PytestExperimentalApiWarning
