[pytest]
python_files = pytest_*.py
addopts =
  --strict-markers

markers =
  esp32: run on ESP32 hardware
  integration: production firmware integration tests

filterwarnings =
  ignore::_pytest.warning_types.PytestExperimentalApiWarning
